name: flutter_huellitas_lm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  cached_network_image: ^3.3.1
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.3
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo-huellitas.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
